# -*- coding: utf-8 -*-
"""Untitled1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1lPuoudFUhHHNcvJP8yNia34pl9iCzP4L
"""

print("hello python") #print hello python
a=10
print("a value is",a) #print 10
