# -*- coding: utf-8 -*-
"""1.2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1wmgtrcMaibjuYSuvvzxhBxFsKRkZCcRb
"""

a=5
b=6
print(a,b)
