# -*- coding: utf-8 -*-
"""2.1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1wmgtrcMaibjuYSuvvzxhBxFsKRkZCcRb
"""

x1=int(input("enter a value"))
y1=int(input("enter a value"))
x2=int(input("enter a value"))
y2=int(input("enter a value"))
d=((x1-x2)**2-(y1-y2)**2)**0.5
print(d)
#0.0 is the output
