# -*- coding: utf-8 -*-
"""2.2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1wmgtrcMaibjuYSuvvzxhBxFsKRkZCcRb
"""

import sys
a=int(sys.argv[1]) #5
b=int(sys.srgv[2]) #4
print("sum is",a+b) #9
print("difference is",a-b) #1
print("product is ",a*b)   #20
print("division is ",a/b)  #1.25
