# -*- coding: utf-8 -*-
"""3.1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1wmgtrcMaibjuYSuvvzxhBxFsKRkZCcRb
"""

age=int(input("enter persons age"))
if age>=18 :
  print("eligible for voting")
else :
  print("not eligible for voting")
#enter persons age18
#eligible for voting
