# -*- coding: utf-8 -*-
"""3.2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1wmgtrcMaibjuYSuvvzxhBxFsKRkZCcRb
"""

sequence=["hello","python","world"]
for i in sequence :
  print(i)
#hello
#python
#world
